import React, { useEffect, useState } from 'react'
import styles from  './ExampleImage.module.css'
import { getRandomImages } from '../../backend/storageFunctions';

const ExampleImage = props => {
    const [randomImages, setRandomImages] = useState([])

    useEffect(() => {
        async function getImg() {
            let urls = await getRandomImages(props.numImages)
            setRandomImages(urls)
        }

        getImg()
    }, [props.numImages])

    return (
        <div className={styles.exampleContainer}>
            {randomImages.map((url, i) => {
                console.log(url)
                return (
                    <div className={styles.container}>
                        <img key={i} src={url} className={styles.loadedImage} alt="Generated by stable diffusion"/>
                    </div>
                )
            })}
        </div>
);
}

export default ExampleImage