import React from "react";
import { Link } from "react-router-dom";
import styles from './home.module.css'

function HomePage() {
    return (
        <div class={styles.pageContainer}>
            <div className={styles.sidebar}>
                {/* List of old queries */}

                <div class={styles.account}>
                    <Link to="/login" style={{textDecoration: 'none'}}>
                        <span class={styles.login}>Log in</span>
                    </Link>
                    <Link to="/register" style={{textDecoration: 'none'}}>
                        <span class={styles.register}>Sign Up</span>
                    </Link>
                </div>
            </div>
            <div className={styles.content}>
                <div className={styles.welcome}>
                    <h1>Generative AAC</h1>
                    <p>Jeremy Cavallo</p>
                </div>
                <div className={styles.promptContainer}>
                    <div className={styles.promptBar}>
                        <input type="text" className={styles.prompt} placeholder="Enter a prompt" />
                        <svg height="20" width="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="none" class={styles.submitSvg} stroke-width="2"><path d="M.5 1.163A1 1 0 0 1 1.97.28l12.868 6.837a1 1 0 0 1 0 1.766L1.969 15.72A1 1 0 0 1 .5 14.836V10.33a1 1 0 0 1 .816-.983L8.5 8 1.316 6.653A1 1 0 0 1 .5 5.67V1.163Z" fill="currentColor"></path></svg>
                    </div>
                    <p className={styles.warning}>Images generated by AI may have artifacts that conflict with human interpretations</p>
                </div>
            </div>
        </div>
    );
}

export default HomePage;
